spring.application.name=api

spring.data.mongodb.uri=mongodb+srv://harvest_link:7fPajnR8uXAoqQ2Q@cluster0.uao8w4o.mongodb.net/harvestlink_db?retryWrites=true&w=majority

application.security.jwt.secret-key=597143543677397A24432646294A404E635266556A586E3272357538782F413F

